version: '2'

networks:
  app-tier:
    driver: bridge

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    networks:
      - app-tier
    ports:
      - 5432:5432
    environment:
    - POSTGRESQL_PASSWORD=123456
    - POSTGRESQL_USERNAME=post
    - POSTGRESQL_PORT_NUMBER=5432
